### ISSUE TITLE
Transaction fees are incorrect

### ISSUE THREAD

**Issue by Isabello** [blockpool-io/bpl-client#3]
When attempting to register a delegate, the fees are labeled as "too low" in the software:

```
bpl 127.0.0.1:4000> account delegate isabella
passphrase: *****************************************************************************
Failed to send transaction: Transaction fee is too low
```

This is not an issue with send transactions.

**Comment by Isabello** [comment]
Reported upstream at the issue source:

https://github.com/blockpool-io/BPL-js/issues/3

**Comment by cyrus19901** [comment]
The transaction fee has been changed to 25BPL from 10BPL
